services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db 
      - cache
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: backend
      POSTGRES_PASSWORD: psswd
      POSTGRES_USER: user
    volumes:
      - ./.postgres-data/db:/var/lib/postgresql/data 
  
  cache:
    image: redis:latest
    restart: always
    volumes:
      - ./.redis/data/:/root/redis
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16